### ISSUE TITLE
Bug: dmabuf patch hangs after a couple minutes

### ISSUE THREAD

**Issue by mrxz** [mrxz/webxr-linux#3]
It seems that the dmabuf approach can freeze up (crash?) after a while. There doesn't seem to be any rhyme or reason to it. Probably a race condition or synchronization issue. Honestly not too surprising given the hacky nature of the patches, but it's worth investigating if it can be resolved.

From my (limited) testing:
- The WebXR experience freezes (no full crash, nor error in logs)
- Occurs anywhere between a couple minutes to 1 hour (haven't made it past an hour since)
- Didn't seem to occur at the time the patch was written (either just luck, or changes in FF code base, SteamVR, drivers, etc... might have surfaced the issue)

Also reported by  https://github.com/mrxz/webxr-linux/issues/1#issuecomment-1217939529

**Comment by kilves** [comment]
@mrxz I believe I've found the issue. There's a synchronization problem while copying memory in VRShMem::PushBrowserState/PullBrowserState where geckoGenerationA/B flags go out of sync and lock up the render thread. Solution is as simple as adding memory locks. I'll post a PR when I can
