### ISSUE TITLE
great action ，Whether can run on the android platform

### ISSUE THREAD

**Issue by zhubinsheng** [mrxz/webxr-linux#5]

**Comment by mrxz** [comment]
The scope of this project is only WebXR support in desktop browsers under Linux. The patches in this repo don't really make sense on Android.

If you're interested in WebXR on Android based stand-alone VR headsets, I would recommend you check out Wolvic (https://github.com/Igalia/wolvic). It's a continuation of the discontinued Firefox Reality browser and offers both immersive browsing and WebXR support.

**Comment by zhubinsheng** [comment]
Wolvic will always be a 3d browser, even if you open the webpage of Google search, it will be presented to users in 3d form

**Comment by zhubinsheng** [comment]
I have compiled Chromium to run on the Android platform. In fact, openxr can only be compiled on the window platform. Like the problems you have encountered before, device/vr/openxr references some platform libraries on the window, such as d3d11. I plan to modify the code as you do so that it can normally use the openxr standard library on the Android platform

**Comment by mrxz** [comment]
Wolvic is indeed always immersive, even when browsing the "2D web". In your case, modifying the code yourself to get OpenXR under Android is probably the way to go, albeit quite some work. The Oculus Browser is Chromium based and does use OpenXR, so it most definitely possible.

If you do make any progress, be sure to share it, as I'm sure others would be interested in it as well. If you don't mind, I'm going to close this issue, as Android is out of scope for this repository. In any case, good luck!
